/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as shopRouteRouteImport } from './routes/(shop)/route'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as shopCheckoutRouteImport } from './routes/(shop)/checkout'
import { Route as shopCartRouteImport } from './routes/(shop)/cart'
import { Route as authenticatedDashboardRouteRouteImport } from './routes/(authenticated)/dashboard/route'
import { Route as shopProductsIndexRouteImport } from './routes/(shop)/products/index'
import { Route as authenticatedDashboardIndexRouteImport } from './routes/(authenticated)/dashboard/index'
import { Route as shopProductsSlugRouteImport } from './routes/(shop)/products/$slug'
import { Route as shopOrderSuccessRouteImport } from './routes/(shop)/order/success'
import { Route as shopOrderPendingRouteImport } from './routes/(shop)/order/pending'
import { Route as shopOrderFailureRouteImport } from './routes/(shop)/order/failure'
import { Route as authenticatedDashboardOrdersIndexRouteImport } from './routes/(authenticated)/dashboard/orders/index'
import { Route as authenticatedDashboardOrdersOrderIdRouteImport } from './routes/(authenticated)/dashboard/orders/$orderId'
import { Route as authenticatedDashboardAdminStatsRouteImport } from './routes/(authenticated)/dashboard/admin/stats'
import { Route as authenticatedDashboardAdminProductsIndexRouteImport } from './routes/(authenticated)/dashboard/admin/products/index'
import { Route as authenticatedDashboardAdminOrdersIndexRouteImport } from './routes/(authenticated)/dashboard/admin/orders/index'
import { Route as authenticatedDashboardAdminCustomersIndexRouteImport } from './routes/(authenticated)/dashboard/admin/customers/index'
import { Route as authenticatedDashboardAdminProductsCreateRouteImport } from './routes/(authenticated)/dashboard/admin/products/create'
import { Route as authenticatedDashboardAdminOrdersOrderIdRouteImport } from './routes/(authenticated)/dashboard/admin/orders/$orderId'
import { Route as authenticatedDashboardAdminCustomersCustomerIdRouteImport } from './routes/(authenticated)/dashboard/admin/customers/$customerId'
import { Route as authenticatedDashboardAdminProductsProductIdEditRouteImport } from './routes/(authenticated)/dashboard/admin/products/$productId/edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const shopRouteRoute = shopRouteRouteImport.update({
  id: '/(shop)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const shopCheckoutRoute = shopCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => shopRouteRoute,
} as any)
const shopCartRoute = shopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => shopRouteRoute,
} as any)
const authenticatedDashboardRouteRoute =
  authenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const shopProductsIndexRoute = shopProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => shopRouteRoute,
} as any)
const authenticatedDashboardIndexRoute =
  authenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const shopProductsSlugRoute = shopProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => shopRouteRoute,
} as any)
const shopOrderSuccessRoute = shopOrderSuccessRouteImport.update({
  id: '/order/success',
  path: '/order/success',
  getParentRoute: () => shopRouteRoute,
} as any)
const shopOrderPendingRoute = shopOrderPendingRouteImport.update({
  id: '/order/pending',
  path: '/order/pending',
  getParentRoute: () => shopRouteRoute,
} as any)
const shopOrderFailureRoute = shopOrderFailureRouteImport.update({
  id: '/order/failure',
  path: '/order/failure',
  getParentRoute: () => shopRouteRoute,
} as any)
const authenticatedDashboardOrdersIndexRoute =
  authenticatedDashboardOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardOrdersOrderIdRoute =
  authenticatedDashboardOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardAdminStatsRoute =
  authenticatedDashboardAdminStatsRouteImport.update({
    id: '/admin/stats',
    path: '/admin/stats',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardAdminProductsIndexRoute =
  authenticatedDashboardAdminProductsIndexRouteImport.update({
    id: '/admin/products/',
    path: '/admin/products/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardAdminOrdersIndexRoute =
  authenticatedDashboardAdminOrdersIndexRouteImport.update({
    id: '/admin/orders/',
    path: '/admin/orders/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardAdminCustomersIndexRoute =
  authenticatedDashboardAdminCustomersIndexRouteImport.update({
    id: '/admin/customers/',
    path: '/admin/customers/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardAdminProductsCreateRoute =
  authenticatedDashboardAdminProductsCreateRouteImport.update({
    id: '/admin/products/create',
    path: '/admin/products/create',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardAdminOrdersOrderIdRoute =
  authenticatedDashboardAdminOrdersOrderIdRouteImport.update({
    id: '/admin/orders/$orderId',
    path: '/admin/orders/$orderId',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardAdminCustomersCustomerIdRoute =
  authenticatedDashboardAdminCustomersCustomerIdRouteImport.update({
    id: '/admin/customers/$customerId',
    path: '/admin/customers/$customerId',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardAdminProductsProductIdEditRoute =
  authenticatedDashboardAdminProductsProductIdEditRouteImport.update({
    id: '/admin/products/$productId/edit',
    path: '/admin/products/$productId/edit',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof authenticatedDashboardRouteRouteWithChildren
  '/cart': typeof shopCartRoute
  '/checkout': typeof shopCheckoutRoute
  '/order/failure': typeof shopOrderFailureRoute
  '/order/pending': typeof shopOrderPendingRoute
  '/order/success': typeof shopOrderSuccessRoute
  '/products/$slug': typeof shopProductsSlugRoute
  '/dashboard/': typeof authenticatedDashboardIndexRoute
  '/products': typeof shopProductsIndexRoute
  '/dashboard/admin/stats': typeof authenticatedDashboardAdminStatsRoute
  '/dashboard/orders/$orderId': typeof authenticatedDashboardOrdersOrderIdRoute
  '/dashboard/orders': typeof authenticatedDashboardOrdersIndexRoute
  '/dashboard/admin/customers/$customerId': typeof authenticatedDashboardAdminCustomersCustomerIdRoute
  '/dashboard/admin/orders/$orderId': typeof authenticatedDashboardAdminOrdersOrderIdRoute
  '/dashboard/admin/products/create': typeof authenticatedDashboardAdminProductsCreateRoute
  '/dashboard/admin/customers': typeof authenticatedDashboardAdminCustomersIndexRoute
  '/dashboard/admin/orders': typeof authenticatedDashboardAdminOrdersIndexRoute
  '/dashboard/admin/products': typeof authenticatedDashboardAdminProductsIndexRoute
  '/dashboard/admin/products/$productId/edit': typeof authenticatedDashboardAdminProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/cart': typeof shopCartRoute
  '/checkout': typeof shopCheckoutRoute
  '/order/failure': typeof shopOrderFailureRoute
  '/order/pending': typeof shopOrderPendingRoute
  '/order/success': typeof shopOrderSuccessRoute
  '/products/$slug': typeof shopProductsSlugRoute
  '/dashboard': typeof authenticatedDashboardIndexRoute
  '/products': typeof shopProductsIndexRoute
  '/dashboard/admin/stats': typeof authenticatedDashboardAdminStatsRoute
  '/dashboard/orders/$orderId': typeof authenticatedDashboardOrdersOrderIdRoute
  '/dashboard/orders': typeof authenticatedDashboardOrdersIndexRoute
  '/dashboard/admin/customers/$customerId': typeof authenticatedDashboardAdminCustomersCustomerIdRoute
  '/dashboard/admin/orders/$orderId': typeof authenticatedDashboardAdminOrdersOrderIdRoute
  '/dashboard/admin/products/create': typeof authenticatedDashboardAdminProductsCreateRoute
  '/dashboard/admin/customers': typeof authenticatedDashboardAdminCustomersIndexRoute
  '/dashboard/admin/orders': typeof authenticatedDashboardAdminOrdersIndexRoute
  '/dashboard/admin/products': typeof authenticatedDashboardAdminProductsIndexRoute
  '/dashboard/admin/products/$productId/edit': typeof authenticatedDashboardAdminProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(shop)': typeof shopRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/(authenticated)/dashboard': typeof authenticatedDashboardRouteRouteWithChildren
  '/(shop)/cart': typeof shopCartRoute
  '/(shop)/checkout': typeof shopCheckoutRoute
  '/(shop)/order/failure': typeof shopOrderFailureRoute
  '/(shop)/order/pending': typeof shopOrderPendingRoute
  '/(shop)/order/success': typeof shopOrderSuccessRoute
  '/(shop)/products/$slug': typeof shopProductsSlugRoute
  '/(authenticated)/dashboard/': typeof authenticatedDashboardIndexRoute
  '/(shop)/products/': typeof shopProductsIndexRoute
  '/(authenticated)/dashboard/admin/stats': typeof authenticatedDashboardAdminStatsRoute
  '/(authenticated)/dashboard/orders/$orderId': typeof authenticatedDashboardOrdersOrderIdRoute
  '/(authenticated)/dashboard/orders/': typeof authenticatedDashboardOrdersIndexRoute
  '/(authenticated)/dashboard/admin/customers/$customerId': typeof authenticatedDashboardAdminCustomersCustomerIdRoute
  '/(authenticated)/dashboard/admin/orders/$orderId': typeof authenticatedDashboardAdminOrdersOrderIdRoute
  '/(authenticated)/dashboard/admin/products/create': typeof authenticatedDashboardAdminProductsCreateRoute
  '/(authenticated)/dashboard/admin/customers/': typeof authenticatedDashboardAdminCustomersIndexRoute
  '/(authenticated)/dashboard/admin/orders/': typeof authenticatedDashboardAdminOrdersIndexRoute
  '/(authenticated)/dashboard/admin/products/': typeof authenticatedDashboardAdminProductsIndexRoute
  '/(authenticated)/dashboard/admin/products/$productId/edit': typeof authenticatedDashboardAdminProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard'
    | '/cart'
    | '/checkout'
    | '/order/failure'
    | '/order/pending'
    | '/order/success'
    | '/products/$slug'
    | '/dashboard/'
    | '/products'
    | '/dashboard/admin/stats'
    | '/dashboard/orders/$orderId'
    | '/dashboard/orders'
    | '/dashboard/admin/customers/$customerId'
    | '/dashboard/admin/orders/$orderId'
    | '/dashboard/admin/products/create'
    | '/dashboard/admin/customers'
    | '/dashboard/admin/orders'
    | '/dashboard/admin/products'
    | '/dashboard/admin/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/cart'
    | '/checkout'
    | '/order/failure'
    | '/order/pending'
    | '/order/success'
    | '/products/$slug'
    | '/dashboard'
    | '/products'
    | '/dashboard/admin/stats'
    | '/dashboard/orders/$orderId'
    | '/dashboard/orders'
    | '/dashboard/admin/customers/$customerId'
    | '/dashboard/admin/orders/$orderId'
    | '/dashboard/admin/products/create'
    | '/dashboard/admin/customers'
    | '/dashboard/admin/orders'
    | '/dashboard/admin/products'
    | '/dashboard/admin/products/$productId/edit'
  id:
    | '__root__'
    | '/'
    | '/(authenticated)'
    | '/(shop)'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/(authenticated)/dashboard'
    | '/(shop)/cart'
    | '/(shop)/checkout'
    | '/(shop)/order/failure'
    | '/(shop)/order/pending'
    | '/(shop)/order/success'
    | '/(shop)/products/$slug'
    | '/(authenticated)/dashboard/'
    | '/(shop)/products/'
    | '/(authenticated)/dashboard/admin/stats'
    | '/(authenticated)/dashboard/orders/$orderId'
    | '/(authenticated)/dashboard/orders/'
    | '/(authenticated)/dashboard/admin/customers/$customerId'
    | '/(authenticated)/dashboard/admin/orders/$orderId'
    | '/(authenticated)/dashboard/admin/products/create'
    | '/(authenticated)/dashboard/admin/customers/'
    | '/(authenticated)/dashboard/admin/orders/'
    | '/(authenticated)/dashboard/admin/products/'
    | '/(authenticated)/dashboard/admin/products/$productId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  shopRouteRoute: typeof shopRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(shop)': {
      id: '/(shop)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof shopRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(shop)/checkout': {
      id: '/(shop)/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof shopCheckoutRouteImport
      parentRoute: typeof shopRouteRoute
    }
    '/(shop)/cart': {
      id: '/(shop)/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof shopCartRouteImport
      parentRoute: typeof shopRouteRoute
    }
    '/(authenticated)/dashboard': {
      id: '/(authenticated)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authenticatedDashboardRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(shop)/products/': {
      id: '/(shop)/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof shopProductsIndexRouteImport
      parentRoute: typeof shopRouteRoute
    }
    '/(authenticated)/dashboard/': {
      id: '/(authenticated)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof authenticatedDashboardIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(shop)/products/$slug': {
      id: '/(shop)/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof shopProductsSlugRouteImport
      parentRoute: typeof shopRouteRoute
    }
    '/(shop)/order/success': {
      id: '/(shop)/order/success'
      path: '/order/success'
      fullPath: '/order/success'
      preLoaderRoute: typeof shopOrderSuccessRouteImport
      parentRoute: typeof shopRouteRoute
    }
    '/(shop)/order/pending': {
      id: '/(shop)/order/pending'
      path: '/order/pending'
      fullPath: '/order/pending'
      preLoaderRoute: typeof shopOrderPendingRouteImport
      parentRoute: typeof shopRouteRoute
    }
    '/(shop)/order/failure': {
      id: '/(shop)/order/failure'
      path: '/order/failure'
      fullPath: '/order/failure'
      preLoaderRoute: typeof shopOrderFailureRouteImport
      parentRoute: typeof shopRouteRoute
    }
    '/(authenticated)/dashboard/orders/': {
      id: '/(authenticated)/dashboard/orders/'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof authenticatedDashboardOrdersIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/orders/$orderId': {
      id: '/(authenticated)/dashboard/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/dashboard/orders/$orderId'
      preLoaderRoute: typeof authenticatedDashboardOrdersOrderIdRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/admin/stats': {
      id: '/(authenticated)/dashboard/admin/stats'
      path: '/admin/stats'
      fullPath: '/dashboard/admin/stats'
      preLoaderRoute: typeof authenticatedDashboardAdminStatsRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/admin/products/': {
      id: '/(authenticated)/dashboard/admin/products/'
      path: '/admin/products'
      fullPath: '/dashboard/admin/products'
      preLoaderRoute: typeof authenticatedDashboardAdminProductsIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/admin/orders/': {
      id: '/(authenticated)/dashboard/admin/orders/'
      path: '/admin/orders'
      fullPath: '/dashboard/admin/orders'
      preLoaderRoute: typeof authenticatedDashboardAdminOrdersIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/admin/customers/': {
      id: '/(authenticated)/dashboard/admin/customers/'
      path: '/admin/customers'
      fullPath: '/dashboard/admin/customers'
      preLoaderRoute: typeof authenticatedDashboardAdminCustomersIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/admin/products/create': {
      id: '/(authenticated)/dashboard/admin/products/create'
      path: '/admin/products/create'
      fullPath: '/dashboard/admin/products/create'
      preLoaderRoute: typeof authenticatedDashboardAdminProductsCreateRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/admin/orders/$orderId': {
      id: '/(authenticated)/dashboard/admin/orders/$orderId'
      path: '/admin/orders/$orderId'
      fullPath: '/dashboard/admin/orders/$orderId'
      preLoaderRoute: typeof authenticatedDashboardAdminOrdersOrderIdRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/admin/customers/$customerId': {
      id: '/(authenticated)/dashboard/admin/customers/$customerId'
      path: '/admin/customers/$customerId'
      fullPath: '/dashboard/admin/customers/$customerId'
      preLoaderRoute: typeof authenticatedDashboardAdminCustomersCustomerIdRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/admin/products/$productId/edit': {
      id: '/(authenticated)/dashboard/admin/products/$productId/edit'
      path: '/admin/products/$productId/edit'
      fullPath: '/dashboard/admin/products/$productId/edit'
      preLoaderRoute: typeof authenticatedDashboardAdminProductsProductIdEditRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
  }
}

interface authenticatedDashboardRouteRouteChildren {
  authenticatedDashboardIndexRoute: typeof authenticatedDashboardIndexRoute
  authenticatedDashboardAdminStatsRoute: typeof authenticatedDashboardAdminStatsRoute
  authenticatedDashboardOrdersOrderIdRoute: typeof authenticatedDashboardOrdersOrderIdRoute
  authenticatedDashboardOrdersIndexRoute: typeof authenticatedDashboardOrdersIndexRoute
  authenticatedDashboardAdminCustomersCustomerIdRoute: typeof authenticatedDashboardAdminCustomersCustomerIdRoute
  authenticatedDashboardAdminOrdersOrderIdRoute: typeof authenticatedDashboardAdminOrdersOrderIdRoute
  authenticatedDashboardAdminProductsCreateRoute: typeof authenticatedDashboardAdminProductsCreateRoute
  authenticatedDashboardAdminCustomersIndexRoute: typeof authenticatedDashboardAdminCustomersIndexRoute
  authenticatedDashboardAdminOrdersIndexRoute: typeof authenticatedDashboardAdminOrdersIndexRoute
  authenticatedDashboardAdminProductsIndexRoute: typeof authenticatedDashboardAdminProductsIndexRoute
  authenticatedDashboardAdminProductsProductIdEditRoute: typeof authenticatedDashboardAdminProductsProductIdEditRoute
}

const authenticatedDashboardRouteRouteChildren: authenticatedDashboardRouteRouteChildren =
  {
    authenticatedDashboardIndexRoute: authenticatedDashboardIndexRoute,
    authenticatedDashboardAdminStatsRoute:
      authenticatedDashboardAdminStatsRoute,
    authenticatedDashboardOrdersOrderIdRoute:
      authenticatedDashboardOrdersOrderIdRoute,
    authenticatedDashboardOrdersIndexRoute:
      authenticatedDashboardOrdersIndexRoute,
    authenticatedDashboardAdminCustomersCustomerIdRoute:
      authenticatedDashboardAdminCustomersCustomerIdRoute,
    authenticatedDashboardAdminOrdersOrderIdRoute:
      authenticatedDashboardAdminOrdersOrderIdRoute,
    authenticatedDashboardAdminProductsCreateRoute:
      authenticatedDashboardAdminProductsCreateRoute,
    authenticatedDashboardAdminCustomersIndexRoute:
      authenticatedDashboardAdminCustomersIndexRoute,
    authenticatedDashboardAdminOrdersIndexRoute:
      authenticatedDashboardAdminOrdersIndexRoute,
    authenticatedDashboardAdminProductsIndexRoute:
      authenticatedDashboardAdminProductsIndexRoute,
    authenticatedDashboardAdminProductsProductIdEditRoute:
      authenticatedDashboardAdminProductsProductIdEditRoute,
  }

const authenticatedDashboardRouteRouteWithChildren =
  authenticatedDashboardRouteRoute._addFileChildren(
    authenticatedDashboardRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedDashboardRouteRoute: typeof authenticatedDashboardRouteRouteWithChildren
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedDashboardRouteRoute:
    authenticatedDashboardRouteRouteWithChildren,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface shopRouteRouteChildren {
  shopCartRoute: typeof shopCartRoute
  shopCheckoutRoute: typeof shopCheckoutRoute
  shopOrderFailureRoute: typeof shopOrderFailureRoute
  shopOrderPendingRoute: typeof shopOrderPendingRoute
  shopOrderSuccessRoute: typeof shopOrderSuccessRoute
  shopProductsSlugRoute: typeof shopProductsSlugRoute
  shopProductsIndexRoute: typeof shopProductsIndexRoute
}

const shopRouteRouteChildren: shopRouteRouteChildren = {
  shopCartRoute: shopCartRoute,
  shopCheckoutRoute: shopCheckoutRoute,
  shopOrderFailureRoute: shopOrderFailureRoute,
  shopOrderPendingRoute: shopOrderPendingRoute,
  shopOrderSuccessRoute: shopOrderSuccessRoute,
  shopProductsSlugRoute: shopProductsSlugRoute,
  shopProductsIndexRoute: shopProductsIndexRoute,
}

const shopRouteRouteWithChildren = shopRouteRoute._addFileChildren(
  shopRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  shopRouteRoute: shopRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
